---
title: "SharePointR: SharePoint and OneDrive in R"
author: Hong Ooi
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{SharePointR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{utf8}
---

SharePointR is a simple yet powerful interface to [SharePoint 365](https://www.microsoft.com/en-au/microsoft-365/sharepoint/collaboration) sites and [OneDrive](https://www.microsoft.com/en-au/microsoft-365/onedrive/online-cloud-storage), leveraging the facilities provided by the [AzureGraph](https://cran.r-project.org/package=AzureGraph) package. Both personal OneDrive and OneDrive for Business are supported.

## OneDrive

To access your personal OneDrive, call the `personal_onedrive()` function. This uses your Internet browser to authenticate with OneDrive, in a similar manner to other web apps. You will see a screen asking you to grant permission for the AzureR Graph app to access your information.

Once the authentication is complete, `personal_onedrive()` returns an R6 client object of class `ms_drive`, which has methods for working with files and folders.

```r
od <- personal_onedrive()

# list files and folders
od$list_items()
od$list_items("Documents")

# upload and download files
od$download_file("Documents/myfile.docx")
od$upload_file("somedata.xlsx")

# create a folder
od$create_folder("Documents/newfolder")
```

You can open a file or folder in your browser with the `open_item()` method. For example, assuming you have a Microsoft 365 (formerly known as Office 365) license, a Word document or Excel spreadsheet will open in Word or Excel Online, and a folder will be shown in OneDrive.

```r
od$open_item("Documents/myfile.docx")
```

You can look at the metadata properties for a file or folder with `get_item_properties()`. This returns an R6 object of class `ms_drive_item`; the properties themselves can be found under the `properties` field. One notable file property is `@microsoft.graph.downloadUrl`, which is an Internet URL from which to download the file. Be careful though: this URL is accessible by _anyone_, so don't share a link for a file you want to remain private!

```r
file_props <- od$get_item_properties("Documents/myfile.docx")

# all metadata is stored as a list in 'properties'
file_props$properties

# public download link for a file -- don't give it out if the file should remain private
file_props$properties$`@microsoft.graph.downloadUrl`
```

Similarly, you can change the metadata for a file with `set_item_properties()`. Provide the new properties as named arguments to the method. Not all properties can be changed; some, like the file size and last modified date, are read-only.

```r
# rename a file
od$set_item_properties("Document/myfile.docx", name="myfile version 2.docx")

# alternatively, you can call the file object's update() method
file_props$update(name="myfile version 2.docx")
```

To access OneDrive for Business call `business_onedrive()`. This also returns an object of class `ms_drive`, so the exact same methods are available as for personal OneDrive. Note that OneDrive for Business is technically part of SharePoint and requires a Microsoft 365 Business license.

```r
odb <- business_onedrive()

odb$list_items()
odb$open_item("myproject/demo.pptx")
```

## SharePoint

To access a SharePoint site, use the `sharepoint_site()` function and provide the site URL or ID. For SharePoint Online, the URL will typically be of the form "https://myaadtenant.sharepoint.com/sites/my-site-name".

```r
site <- sharepoint_site("https://myaadtenant.sharepoint.com/sites/my-site-name")
```

The client object has methods to retrieve drives and lists. To show all drives in a site, use the `list_drives()` method, and to retrieve a specific drive, use `get_drive()`. Each drive is an object of class `ms_drive`, just like the OneDrive clients above.

```r
# list of all document libraries under this site
site$list_drives()

# default document library
drv <- site$get_drive()

# same methods as for OneDrive
drv$list_items()
drv$open_item("Documents/myfile.docx")
```

To show all lists in a site, use the `get_lists()` method, and to retrieve a specific list, use `get_list()` and supply either the list name or ID.

```r
site$get_lists()

lst <- site$get_list("my-list")
```

You can retrieve the items in a list as a data frame, with `list_items()`. This has arguments `filter` and `select` to do row and column subsetting respectively. `filter` should be a row filtering OData expression provided as a string, and `select` should be a string containing a comma-separated list of columns.

For technical reasons, any column names in the `filter` argument must have `fields/` in front of them; this requirement may be removed in a future version of SharePointR. For more information, see the [Graph API documentation](https://docs.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2F1.0&view=graph-rest-1.0). Similarly, due to limitations in the Microsoft Graph REST API version 1.0, you can currently only read data from lists, not write to them.

```r
# return a data frame containing all list items
lst$list_items()

# get subset of rows and columns
lst$list_items(
    filter="startsWith(fields/firstname, 'John')",
    select="firstname,lastname,title"
)
```

Finally, you can retrieve subsites with `list_subsites()` and `get_subsite()`. These also return SharePoint site objects, so all the methods above are available for a subsite.

Currently, SharePointR only supports SharePoint Online, the cloud-hosted version of the product. Support for SharePoint Server (the on-premises version) may come at a later stage.

## Integration with AzureGraph

In addition to the client functions given above, SharePointR enhances the `az_user` and `az_group` classes that are part of AzureGraph, to let you access drives and sites directly from a user or group object.

`az_user` gains `list_drives()` and `get_drive()` methods. The first shows all the drives that the user has access to, including those that are shared from other users. The second retrieves a specific drive, by default the user's OneDrive. Whether these are personal or business drives depends on the tenant that was specified in `AzureGraph::get_graph_login()`/`create_graph_login()`: if the tenant was "consumers", it will be the personal OneDrive.

`az_group` gains `list_drives()`, `get_drive()` and `get_sharepoint_site()` methods. The first two do the same as for `az_user`: they retrieve the drive(s) for the group. The third method retrieves the SharePoint site associated with the group, if one exists.

## Authentication troubleshooting

SharePointR's default authentication flow leverages your Internet browser to provide the same login experience as other web apps. This may be a problem if your R session is taking place in a context where a browser is unavailable, for example in a text-only terminal in a VM or container. If so, you can switch to the device code flow, by adding `auth_type="device_code"` as an argument:

```r
personal_onedrive(auth_type="device_code")

business_onedrive(auth_type="device_code")

sharepoint_site("https://site-url", auth_type="device_code")
```

When authenticating for SharePoint and OneDrive for Business, by default SharePointR will detect your Azure Active Directory tenant from your logged-in credentials in the browser. If this doesn't work, specify your tenant name with the `tenant` argument:

```r
business_onedrive(tenant="myaadtenant")

sharepoint_site("https://site-url", tenant="myaadtenant")
```

